### ISSUE TITLE
Firefox installation?

### ISSUE THREAD

**Issue by astradamus** [cleanlock/VideoAdBlockForTwitch#10]
Are you guys intending to set this up for Firefox as well, or is it already possible to install? I know nothing about browser extensions, or how cross-compatible development is for one versus the other, so obviously no worries if you're not :P

**Comment by cleanlock** [comment]
Hi, at the moment the Chrome extension is in the focus. Firefox will come later. :)

**Comment by astradamus** [comment]
Awesome! Good to know, thanks for working on this :P

**Comment by kdjmonaghan** [comment]
Firefox version has been added, this can now be closed: https://addons.mozilla.org/en-US/firefox/addon/twitch-adblock/

@cleanlock
