### ISSUE TITLE
Manifest v3 Update

### ISSUE THREAD

**Issue by cleanlock** [cleanlock/VideoAdBlockForTwitch#12]
Hi everyone,

so this extension is based on Manifest v2 still and it needs to be updated to Manifest v3 in order to get it published on the Chrome Webstore. @HatterTheMadd has pushed some stuff to the dev-Branch for Manifest v3.

Unfortunately, Manifest v3 doesn't allow inline-scripts anymore.

Edit: Update has been pushed.

**Comment by cleanlock** [comment]
Hello again!

I just pushed an update to the dev-Branch! It seems like I've got it working. Twitch Ads are being blocked in the latest version of the dev-Branch. This is another step direction Chrome Webstore!

**Comment by cleanlock** [comment]
Update has been pushed to the master-branch now. If you encounter any issues, please open an issue. :)

**Comment by Mahir007** [comment]
Is there any chance this will be published on the 'Microsoft Edge Add-ons' site as well?

**Comment by DannyDarth** [comment]
Why was there an amazon referal link added to this blocker? Seems kinda sus to me.

**Comment by cleanlock** [comment]
Extension is available for Chrome and Firefox.
