### ISSUE TITLE
Discord Server for Support & exchange

### ISSUE THREAD

**Issue by cleanlock** [cleanlock/VideoAdBlockForTwitch#15]
Heya!

I've created a Discord Server for support and general exchange. Feel free to join :)

https://discord.gg/PSgWqf3v8V

**Comment by rainlizard** [comment]
the link expired

**Comment by cleanlock** [comment]
> the link expired

Fixed. Thanks!

**Comment by cleanlock** [comment]
Added Discord server to README.md
