### ISSUE TITLE
New versions dont work and only 5.3.4 works

### ISSUE THREAD

**Issue by LemonDoo** [cleanlock/VideoAdBlockForTwitch#26]
Updated google chrome and used load unpacked

**Comment by cleanlock** [comment]
Should be fixed.

Please try v5.3.8 and make sure that you load the "chrome"-Folder

**Comment by LemonDoo** [comment]
Nope v5.3.8 also doesn't work

Loads forever when trying to play live streams

**Comment by cleanlock** [comment]
Please make sure that every single Tampermonkey script, which are designed for Adblock on Twitch, is disabled
