### ISSUE TITLE
UBlock Origin Script Version

### ISSUE THREAD

**Issue by Kromppo** [cleanlock/VideoAdBlockForTwitch#31]
The current version of this for UBlock Origin is [pixeltris version](https://github.com/pixeltris/TwitchAdSolutions#applying-a-script-ublock-origin) which he said isn't going to be maintained. Are there any plans to create a script version of this to be used instead of a extension? Or is there a github link to use that will get updated when the repo is updated?

**Comment by cleanlock** [comment]
Hi,

no there are no plans to maintain a script version.

**Comment by pixeltris** [comment]
I will be pulling in any changes which are made to the logic of the code in `remove_video_ads.js`. For now it's staying on 5.3.5 as there haven't been any logic changes.
