### ISSUE TITLE
"Blocking Ads" message Off / On doesn't work

### ISSUE THREAD

**Issue by DavidBrazSan** [cleanlock/VideoAdBlockForTwitch#33]
Even enabled not hidden.
My browser is Firefox 98.0.2 (64-bit)

**Comment by cleanlock** [comment]
Seems like it never really worked for Firefox. I only re-designed the Design on the Firefox-Version. I'll check if I can get it working, can't promise tho

**Comment by cleanlock** [comment]
Just looked further into this. It seems like the Message disappears after around ~1-2 seconds. This happens on Chrome and Firefox.

This should be fine.

**Comment by DavidBrazSan** [comment]
still be showing up

**Comment by cleanlock** [comment]
I've tested it several times. The message takes a few seconds to disappear, but it disappears if you choose so.

**Comment by DavidBrazSan** [comment]
You're hiding here too.
My doubt is that this option should not show the message.

**Comment by cleanlock** [comment]
I have reworked the logic and pushed the update.

Enabled = shows the message
Disabled = hides the message

Before it was:

Enabled = hides the message
Disabled = shows the message

Which was simply wrong according to the menu.

But as I said, if you set the option to disabled, the message will still show up for a few seconds, and I think that's totally fine.

**Comment by DavidBrazSan** [comment]
It's no problem for me. Think it could be an extension bug.

**Comment by cleanlock** [comment]
As I described it, it's not a bug.
