### ISSUE TITLE
Make sure to rate the Extension on Firefox & Chrome

### ISSUE THREAD

**Issue by cleanlock** [cleanlock/VideoAdBlockForTwitch#35]
Heya!

Please make sure that you rate the extension on Firefox & Chrome, so it gets more attention :)

Only rate for the browser you're using. Thanks <3

**Comment by Catwoman1980** [comment]
I loved this

**Comment by Mahir007** [comment]
Just fyi, the extension has been approved for Edge and is up on the 'Edge Add-ons' site as well. So guys, don't forget to rate & review it there as well !

**Comment by cleanlock** [comment]
> Just fyi, the extension has been approved for Edge and is up on the 'Edge Add-ons' site as well. So guys, don't forget to rate & review it there as well !

I know, but v5.4.0 is still in review. :)
