### ISSUE TITLE
Resolution issue

### ISSUE THREAD

**Issue by pixeltris** [cleanlock/VideoAdBlockForTwitch#36]
I saw some comments about the extension defaulting to 360p which I was able to reproduce. The code attempts to restore the original set quality, but doesn't quite get it right. A simpler approach is to restore the value currently set in `localStorage`.

Current code:

https://github.com/cleanlock/VideoAdBlockForTwitch/blob/7234bf4a73271d368d9f28328d515bb541620fa0/chrome/remove_video_ads.js#L217-L220

Should be changed to:

```js
var currentQualityLS = window.localStorage.getItem('video-quality');
lowQuality[qualityToSelect].click();
window.localStorage.setItem('video-quality', currentQualityLS);
```

From my brief testing this seems to fix the issue.

**Comment by cleanlock** [comment]
Thank you for providing this fix! I've merged it :)
