### ISSUE TITLE
Why are all of these required and not just the first one?

### ISSUE THREAD

**Issue by jerbanpls** [cleanlock/VideoAdBlockForTwitch#38]
![image](https://user-images.githubusercontent.com/103174411/162856863-53f5efe5-8541-47ae-b0a1-1f102427e24d.png)

**Comment by CourteousGeek** [comment]
Those domain do look like they are being blocked when i'm on the network tab
![librewolf_POy3zCJgEj](https://user-images.githubusercontent.com/77457021/162858422-708f6847-b597-4779-9b8e-9695aa63967c.png)
.
