### ISSUE TITLE
Twitch player buffering in loop each Chrome's fresh start

### ISSUE THREAD

**Issue by thekillgfx** [cleanlock/VideoAdBlockForTwitch#39]
```
Chrome Version: 100.0.4896.88 (Official Build) (64 bit)
Twitch Adblock Version: 5.4.0
```

**Issue**
Every time I start Chrome for the first time, next to the OS boot, once I load a Twitch page the player keeps buffering in loop.

**Workaround**
In order to solve the issue I discovered the following steps

- turn off Twitch Adblocker via its first setting
- reload Twitch page

_now Twitch's player loads properly_
- turn on Twitch Adbloacker via its first setting
- reload Twitch page

_now Twitch's players is working properly and so does the Twitch Adblocker_

**Comment by cleanlock** [comment]
Not an extension issue.

Q: Why are streams not loading anymore after installing the extension?
A: Please make sure that you have disabled/removed any Scripts (Tampermonkey, uBlock, ...) / Extensions which intend to block ads on Twitch.

**Comment by thekillgfx** [comment]
Thanks, I was sure that all the other extensions were gone but some were not!

**Comment by cleanlock** [comment]
Glad it works! :)
