### ISSUE TITLE
Can't turn quality down lower than 480p whilst ads are being blocked

### ISSUE THREAD

**Issue by HanPrower** [cleanlock/VideoAdBlockForTwitch#40]
Browser: Firefox 99.0.1
Addon: v5.4.1

Bit of an odd one, I guess, but a bug either way.

Still seems to drop down to the lower resolution after blocking ads, however.

Does make me wonder if a mid-roll happens if it turns the quality up to 480p 🤔 Generally not physically watching a stream when I've set it to 160p to notice.

**Comment by cavin8** [comment]
Also seeing this.

Chrome: 100.0.4896.88 & 100.0.4896.127
Extension: 5.4.0

**Comment by pixeltris** [comment]
The reason this happens is because there was a bug under firefox where the stream would break (audio normal, video frozen). The fix requires changing the resolution to 480p while ads are playing. As such you can't change it off 480p during the ad.

It would be possible to skip that code on chrome as it doesn't have the playback bug that happens on firefox. But firefox requires that code.

**Comment by cleanlock** [comment]
I'll look into this soon (for Chrome).

**Comment by ItzJustSamuel** [comment]
Opera GT has the same issue

**Comment by privacyguy123** [comment]
I'm noticing quality locked to 480 while an ad playing also - Firefox 100

**Comment by TheRayJohnson** [comment]
> I experience the same issue, but if I select 1080p (low latency or not), then in a few minutes it'll switch to 1080p.
> 
> Based on what I've looked at in the code, the extension will set the quality to 480p until all ads have been blocked, and then sets it back to the original quality.

Mine will go to 480p but won't ever return to the original quality? Even after an hour or what not. Second I re-select 1080p within 6 seconds its back 480p. Annoying cause game looks awful lol.

**Comment by pixeltris** [comment]
@cleanlock FYI this will still occur on Firefox as the forced resolution change is still enabled there (to fix freezing issues).

**Comment by cleanlock** [comment]
Oh, good to know. Thanks for the info!
