### ISSUE TITLE
Add Safari Support (MacOS + iOS/iPadOS)

### ISSUE THREAD

**Issue by LotharieSlayer** [cleanlock/VideoAdBlockForTwitch#41]
All is in the title, for iOS if you can’t upload it on App Store there is [Makeover](https://apps.apple.com/fr/app/makeover-custom-css/id1602361167) which is a bit like a Tampermonkey but for iOS.

**Comment by cleanlock** [comment]
You might want to check out TwitchAdSolutions: https://github.com/pixeltris/TwitchAdSolutions

There are scripts for Tampermonkey etc.
