### ISSUE TITLE
Service worker inactivity issue

### ISSUE THREAD

**Issue by trivenge** [cleanlock/VideoAdBlockForTwitch#42]
Using brave I noticed that the service worker becomes inactive in the middle of twitch streams, the fix atm for this is to go into the extensions local page to turn the service worker off and back on again to set it to active. I am unsure if this is forced off via something twitch is doing, but wanted to mention it in the mean time.  Unsure if this is the case for chromium overall or any other browsers currently.

**Comment by pixeltris** [comment]
I think that's an issue with manifest V3. There is a 5 minute window where service workers can be used, after which point they are killed by the browser.

**Comment by trivenge** [comment]
> I think that's an issue with manifest V3. There is a 5 minute window where service workers can be used, after which point they are killed by the browser. https://stackoverflow.com/a/66618269

Thanks for the info, appreciate it. I wonder if there is a workaround. Seems like the only workaround is to refresh the worker via browser extension and then refresh the page to get it working.

**Comment by cleanlock** [comment]
Hey, as @pixeltris said: this is related to Manifest v3.
