### ISSUE TITLE
Feature Request: #2000 error auto refresh

### ISSUE THREAD

**Issue by ksthiele** [cleanlock/VideoAdBlockForTwitch#43]
Hi, 

I'm not sure I'm the only one getting an error #2000 from time to time while blocking ads, that's why I installed an additional extension that auto refreshes the player when the error occurs, it would be nice if it could be an extra option of this extension

**Comment by elmarceloc** [comment]
https://github.com/Dziango/Twitch-Autorefresher-error-2000

**Comment by cleanlock** [comment]
Closed as a solution has been provided.
