### ISSUE TITLE
Video stuck at 480p

### ISSUE THREAD

**Issue by TaylorTWBrown** [cleanlock/VideoAdBlockForTwitch#45]
With the extension enabled, the max resolution I can view twitch with is 480p.

**Comment by cleanlock** [comment]
That's only during ads. If you can't change the quality after ads, it must be something on your end. The extension is working perfectly for me.

**Comment by TaylorTWBrown** [comment]
Interesting, you might be right - it's only stuck at 480p sometimes. I'll play around with it.
