### ISSUE TITLE
VODs/Streams Crashing with Error Code #3000

### ISSUE THREAD

**Issue by RevENGE-code** [cleanlock/VideoAdBlockForTwitch#46]
Browser: Chrome — Version 101.0.4951.41 (Official Build) (64-bit)
Add-on: v5.3.5

Sometime into watching a VOD or Stream of someone, the Twitch Media Player crashes and returns Error Message #3000.

**Comment by cleanlock** [comment]
You should install the extension directly from the Chrome Store.

**Comment by RevENGE-code** [comment]
> You should install the extension directly from the Chrome Store.

I did

**Comment by RevENGE-code** [comment]
> You mentioned the extension version v5.3.5, which is not the version from the Chrome Store. So you're running v5.4.0?

I'll test it out today and let you know.

**Comment by cleanlock** [comment]
Alright. And also a little side note: This extension has been forked as the original author did some shady stuff to the original extension. So please make sure that you have this version installed: https://chrome.google.com/webstore/detail/twitch-adblock/ljhnljhabgjcihjoihakgdiicdjncpkd

**Comment by RevENGE-code** [comment]
Hey,

so I've been testing it for the last week and the issue seems to have disappeared. I've not had another problem with it.

Twitch Adblock-Version: 5.4.0
Chrome Version: 101.0.4951.67

**Comment by RevENGE-code** [comment]
Okay, so I've used it for about a week now, Version 5.4.0 directly from the Chrome Store. The issue still persists, all streams that I watch eventually crash with error Code #3000. 

Chrome Version: Version 101.0.4951.67

**Comment by ujjukumar** [comment]
True I have also had same issue.
