### ISSUE TITLE
Streams not loading with Twitch Adblock enabled.

### ISSUE THREAD

**Issue by Gona2119** [cleanlock/VideoAdBlockForTwitch#49]
I've noticed that with the extension enabled, the streams don't load unless I disable adblock in the extensions setting. The screen stays in a black image with the typical loading circle. No more to add, happens with all type of streams or categories. Greetings and nice extension despite this issue

**Comment by cleanlock** [comment]
Please check carefully all your extensions and scripts. Make sure that only one Twitch Adblocker is running.

**Comment by Gona2119** [comment]
Yes sir, it's the onlyone and got that error with it enabled. I've tryed loading any stream in incognito mode with no extensions loaded and the stream loaded succesfully, and in normal mode the stream loads when I disable this extension

**Comment by cleanlock** [comment]
How about trying to load streams in Incognito mode with the extension enabled? If that works, another script or extension is interfering.

**Comment by cleanlock** [comment]
Closed as this is a user issue.
