### ISSUE TITLE
Twitch player stays permanently loading

### ISSUE THREAD

**Issue by midadami** [cleanlock/VideoAdBlockForTwitch#52]
Started happening today. Twitch player stays permanently loading (wheel turning, black screen) when the blocker is active.

**Comment by dazoe** [comment]
Same issue here, why is this closed?

**Comment by cleanlock** [comment]
Because he closed it.

Please clear your browser cache & cookies.

**Comment by dazoe** [comment]
That did it. I should have tried that first. Thanks
