### ISSUE TITLE
Stream not starting anymore

### ISSUE THREAD

**Issue by d-t-o** [cleanlock/VideoAdBlockForTwitch#53]
Seems twitch changed something, since today, when I open a stream or vod, I only see the buffering symbol and the video never starts. If I disable this extension, it starts right away.

**Comment by cbr600det** [comment]
Same thing happened for me today. I only got the buffering symbol. As soon as I disabled the extension and refreshed Twitch, the stream opened. I guess Twitch changed something to prevent the ad blocker. Thank you guys for working on this repo. We really appreciate it!

**Comment by dph121** [comment]
I have the same issue, except when I use an Incognito window. If I use Incognito, the stream loads without ads as before, even if I'm logged in.

**Comment by d-t-o** [comment]
Good point, clearing the cookies actually makes the video start again upon reload. Not sure for how long this will work though...

**Comment by Vafarien** [comment]
i did some random delete all my cookies thing on twitch, but all my FFZ and other settings are reset!!! this is soo annoying... i do not want to have to reset all setting every time, to just get the stream to play again. :disappointed: 
hopefully the fork makers find some kinda work around to this new twitch loading thingy.

**Comment by cleanlock** [comment]
> i did some random delete all my cookies thing on twitch, but all my FFZ and other settings are reset!!! this is soo annoying... i do not want to have to reset all setting every time, to just get the stream to play again. 😞 hopefully the fork makers find some kinda work around to this new twitch loading thingy.

I understand that this annoys you, but there is nothing else I can offer at the moment as I haven't run into that issue yet. I hope I'll be able to track it down asap, until then you'll have to delete the twitch cookies for now to resolve this issue.

**Comment by Vinnnes** [comment]
From what I've researched, apparently this problem is happening to even people who don't use adblock. From what I've seen, this is a Twitch problem itself.

**Comment by spinalrampage** [comment]
If it helps any, I personally have only had the issue on the Brave browser. Both Firefox and Chrome (though Chrome is on a different computer) work correctly w/ the extension.

**Comment by dobson980** [comment]
> i did some random delete all my cookies thing on twitch, but all my FFZ and other settings are reset!!! this is soo annoying... i do not want to have to reset all setting every time, to just get the stream to play again. 😞 hopefully the fork makers find some kinda work around to this new twitch loading thingy.

can confirm that clearing cookies for twitch site in edge also resolves. Have not seen the buffering issue since.

**Comment by huphan** [comment]
In using Cookie-Editor for Firefox, I only delete `unique_id` and `unique_id_durable` to get the stream working again after refreshing.

**Comment by Vinnnes** [comment]
It was also crashing, but apparently it was more of a problem with Twitch than with Adblock, those who didn't use it also crashed, now everything is fine.

**Comment by dph121** [comment]
Huphan's solution (delete the cookies `unique_id` and `unique_id_durable`) also works for me in Chrome, and it kept my FFZ settings.

**Comment by Arandomnameok** [comment]
Clearing cookies doesnt do anything anymore for me. Further it now constantly pauses the stream which makes it unwatchable or you're lagging behind despite my connection having 0 issues.. it seems twitch patched this. Question did the people making this extension complete drop it? or what's going on?

**Comment by TobiasPettersson** [comment]
I had the same problem so I tried clearing the cookies with no success. I solved it by **turning off uBlock Origin** for Twitch and now it works like a charm!

**Comment by cleanlock** [comment]
Should be fixed.
