### ISSUE TITLE
sometimes getting pre-rolls again

### ISSUE THREAD

**Issue by ricketycricket69** [cleanlock/VideoAdBlockForTwitch#55]
first of all thanks for (re)creating this extension, but sometimes i'm getting pre-roll ads again. Location is Germany. It's just one ad from Allianz. It doesn't happen everytime, so i don't know how hard it is to check this.

OS: Windows 10 64-bit 21H2 (OS Build 19044.1865)
Browser: Chrome 104.0.5112.81

**Comment by DJ-Blockchain** [comment]
Also receiving pre-rolls again. Location is US. If ads start to pre-roll, refreshing the page generates new pre-roll ads. Extension does not intercept them.

OS: Windows 11 64-bit 21H2 (OS Build 22000.795)
Browser: Vivaldi 5.3.2679.70 (Stable channel) (64-bit)

**Comment by cleanlock** [comment]
Please see #57 - not much I can do at this point. I hope I'll find a fix asap.
