### ISSUE TITLE
streams are stuck at 480p now while the ad block is turned on

### ISSUE THREAD

**Issue by dguooo** [cleanlock/VideoAdBlockForTwitch#56]
Watching streams w/ the ad-blocking turned on results in users not being able to go higher than 480p stream quality (both auto and manually selecting 720p, 1080p, etc.). When the ad-blocking is turned off, streams go back to being high-quality.

OS: Windows 11 Pro 64-bit 21H2 (OS Build 22000.795)
Browser: Firefox 103.0.2

**Comment by PaulDoesDev** [comment]
That's how this extension works (potentially _worked_ after today)

"Twitch Adblock blocks ads on Twitch by switching to an ad-free version of the stream at 480p during the ad-time and automatically switches back to the original video quality after the ad-time is over"

**Comment by dguooo** [comment]
Ah I see, I guess I haven't used the extension in a while so I was confused why it wouldn't work how it used to.
