### ISSUE TITLE
adblock not working as of today

### ISSUE THREAD

**Issue by supa42** [cleanlock/VideoAdBlockForTwitch#57]
After opening a stream, it says 'blocking ads' in the top left and all that is shown is a purple-backgrounded still image with the twitch logo at the top and 'commercial break in progress' underneath. This lasts the duration of the ad that would normally play (countdown at top right) then stream opens. Only started happening today, was fine this morning but then it stopped working maybe around 8/9pm BST

**Comment by Piwielle** [comment]
Can confirm. Here's a screenshot of what it looked like.
![unknown](https://user-images.githubusercontent.com/47955122/185506346-491103f4-a34e-4004-87dd-4a61a38e0208.png)

**Comment by thisisdumbstuff** [comment]
Not working here also, as of today. Last night was working

**Comment by john-dev** [comment]
Twitch added this placeholder to low-res streams last night which this addon switched to during ads.
There is nothing that can be done i assume. It won't take long and they show the ad's on low-res too.

**Comment by LostPoE** [comment]
Confirmed.

**Comment by bzlom** [comment]
Same issue on my end.

**Comment by pixeltris** [comment]
Try adding `twitch.tv#@#+js(twitch-videoad)` to your ublock origin filters list.

**Comment by edadams** [comment]
> Try adding `twitch.tv#@#+js(twitch-videoad)` to your ublock origin filters list. [A bit of an explanation of why](https://github.com/pixeltris/TwitchAdSolutions/issues/81#issuecomment-1221014938).

This doesn't work, at least for me. I can add the rule you suggest to the filters list, I can exclude uBlock Origin from working on Twitch via the UI, and I can literally disable uBO from the Chrome extensions config menu - unfortunately nothing works.

**Comment by Zachruff** [comment]
> Try adding `twitch.tv#@#+js(twitch-videoad)` to your ublock origin filters list. [A bit of an explanation of why](https://github.com/pixeltris/TwitchAdSolutions/issues/81#issuecomment-1221014938).

does not work, still showing the commercial break screen when opening a new stream

**Comment by pixeltris** [comment]
Ah ok I guess I was wrong. I haven't been able to re-produce it yet in normal situations. I tried different IPs (UK / US / Canada / Germany) under chrome while not being logged into a Twitch account. None showed it. I'll keep an eye out and see if I can come up with a solution when it happens.

**Comment by gabecastroaz** [comment]
Oh Good I'm not the only one seeing this issue. I had to disable the extension in order to continue watching Twitch as no channels would load. Infinitely sitting on Commercial Break screen.

**Comment by Zachruff** [comment]
> Ah ok I guess I was wrong. I haven't been able to re-produce it yet in normal situations. I tried different IPs (UK / US / Canada / Germany) under chrome while not being logged into a Twitch account. None showed it. I'll keep an eye out and see if I can come up with a solution when it happens.

in my case it seems to be any time i click on a new stream it does this, I don't seem to be getting any midroll ads at least

**Comment by pixeltris** [comment]
It does seem like they are doing some A/B testing. I can reproduce it by deleting my cookies a few times until it occurs. For now deleting your cookies should work to fix it (it might take a few or many attempts). The exact cookie is `unique_id` / `unique_id_durable` which is how they track users / devices.

I can't see an obvious workaround so I think going forward when this comes out of A/B testing I think the proxy solutions will be the only real solution to displaying the stream ASAP. Maybe a hybrid approach could be made where you only proxy during the ad segments for those cannot use the proxies due to the lag. The `embed` method could also be useful here as it does still work sometimes.

**Comment by JoeLinden** [comment]
Clearing cookies and logging back in only works for a few minutes. Log-in status, refreshing, restarting Firefox, logging out & back in while the solution is working, and switching streams didn't affect anything - it just stopped working after being in another FF tab for a bit. The original "low-res stream" still exists, it gets played when you clear cookies. This only happens on pre-rolls AFAIK.

**Comment by dumbfound97** [comment]
> It does seem like they are doing some A/B testing. I can reproduce it by deleting my cookies a few times until it occurs. For now deleting your cookies should work to fix it (it might take a few or many attempts). The exact cookie is `unique_id` / `unique_id_durable` which is how they track users / devices.
> 
> I can't see an obvious workaround so going forward when this comes out of A/B testing I think the proxy solutions will be the only real solution to displaying the stream ASAP. Maybe a hybrid approach could be made where you only proxy during the ad segments for those cannot use the proxies due to the lag. The `embed` method could also be useful here as it does still work sometimes.

You can download this chrome extension: https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en 

You don't have to block those two cookies, just set them to read only

**Comment by dumbfound97** [comment]
> It does seem like they are doing some A/B testing. I can reproduce it by deleting my cookies a few times until it occurs. For now deleting your cookies should work to fix it (it might take a few or many attempts). The exact cookie is `unique_id` / `unique_id_durable` which is how they track users / devices.
> 
> I can't see an obvious workaround so going forward when this comes out of A/B testing I think the proxy solutions will be the only real solution to displaying the stream ASAP. Maybe a hybrid approach could be made where you only proxy during the ad segments for those cannot use the proxies due to the lag. The `embed` method could also be useful here as it does still work sometimes.

You can try this chrome extension to block those cookies or set them to read-only
https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en

**Comment by cleanlock** [comment]
Can confirm that blocking these 2 cookies works.

**Comment by Kamiikaze** [comment]
> > It does seem like they are doing some A/B testing. I can reproduce it by deleting my cookies a few times until it occurs. For now deleting your cookies should work to fix it (it might take a few or many attempts). The exact cookie is `unique_id` / `unique_id_durable` which is how they track users / devices.
> > I can't see an obvious workaround so going forward when this comes out of A/B testing I think the proxy solutions will be the only real solution to displaying the stream ASAP. Maybe a hybrid approach could be made where you only proxy during the ad segments for those cannot use the proxies due to the lag. The `embed` method could also be useful here as it does still work sometimes.
> 
> You can try this chrome extension to block those cookies or set them to read-only. Setting them to read only works best for me (EditThisCookie) https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg?hl=en

I tried to block/delete/read-only the cookie but didnt worked for me

**Comment by tanjamado** [comment]
> Can confirm that blocking these 2 cookies works. (for now)

Not working for me :(

**Comment by cleanlock** [comment]
Are you sure that you have done it correctly? I've done it on a friend's computer and it worked as well.

**Comment by nucombo** [comment]
was a nice ride I guess, time to graduate from twitch because all the ads is just impossible

**Comment by infiniteflow24** [comment]
> > Can confirm that blocking these 2 cookies works. (for now)
> 
> Not working for me :(

it was same for me but use any program (like Ccleaner) and clean them all.
it works well just like before. no more purple image.

**Comment by Kamiikaze** [comment]
> Are you sure that you have done it correctly? I've done it on a friend's computer and it worked as well.

After setting Cookies to read-only and disabled this (AdblockForTwitch Addon) it's working

**Comment by tanjamado** [comment]
> 

Could you tell me how it's done ? Here's a screenshot of the 2 cookies blocked

![image](https://user-images.githubusercontent.com/34989188/186435889-467f4903-b628-4f6b-bc24-c04b5f4fecbb.png)

**Comment by StevensND** [comment]
> > 
> 
> Could you tell me how it's done ? Here's a screenshot of the 2 cookies blocked using the extension EditThisCookie
> 
> ![image](https://user-images.githubusercontent.com/34989188/186435889-467f4903-b628-4f6b-bc24-c04b5f4fecbb.png)

Go to a Twitch stream, open the extension and then protect it. [How To](https://gyazo.com/02b850ece98dce33a315b6ba738d8a7e) 

[Last Screenshot](https://gyazo.com/c58db191a2d5b55cff47435cc7212712)

**Comment by tanjamado** [comment]
> > > 
> > 
> > 
> > Could you tell me how it's done ? Here's a screenshot of the 2 cookies blocked using the extension EditThisCookie
> > ![image](https://user-images.githubusercontent.com/34989188/186435889-467f4903-b628-4f6b-bc24-c04b5f4fecbb.png)
> 
> Go to a Twitch stream, open the extension and then protect it. [How To](https://gyazo.com/02b850ece98dce33a315b6ba738d8a7e)
> 
> [Last Screenshot](https://gyazo.com/c58db191a2d5b55cff47435cc7212712)

![image](https://user-images.githubusercontent.com/34989188/186438913-fb51f63f-5307-4b43-826b-f04c3fad0ec3.png)

**Comment by StevensND** [comment]
> > > > 
> > > 
> > > 
> > > Could you tell me how it's done ? Here's a screenshot of the 2 cookies blocked using the extension EditThisCookie
> > > ![image](https://user-images.githubusercontent.com/34989188/186435889-467f4903-b628-4f6b-bc24-c04b5f4fecbb.png)
> > 
> > 
> > Go to a Twitch stream, open the extension and then protect it. [How To](https://gyazo.com/02b850ece98dce33a315b6ba738d8a7e)
> > [Last Screenshot](https://gyazo.com/c58db191a2d5b55cff47435cc7212712)
> 
> ![image](https://user-images.githubusercontent.com/34989188/186438913-fb51f63f-5307-4b43-826b-f04c3fad0ec3.png)
> 
> For me they re not just read only they re completely blocked.

Click on the arrow as [I show you](https://gyazo.com/2ffc69f6e562e45b05ebaf1e18e144a2)

**Comment by tanjamado** [comment]
![image](https://user-images.githubusercontent.com/34989188/186441067-7d6f1078-4a2d-4c61-92a0-3ffa724da1ad.png)


![image](https://user-images.githubusercontent.com/34989188/186441026-109c60eb-a32f-4f73-9d99-4c66666564d4.png)

**Comment by StevensND** [comment]
> ![image](https://user-images.githubusercontent.com/34989188/186441067-7d6f1078-4a2d-4c61-92a0-3ffa724da1ad.png)
> 
> ![image](https://user-images.githubusercontent.com/34989188/186441026-109c60eb-a32f-4f73-9d99-4c66666564d4.png)

That's how it should look.

**Comment by tanjamado** [comment]
> > ![image](https://user-images.githubusercontent.com/34989188/186441067-7d6f1078-4a2d-4c61-92a0-3ffa724da1ad.png)
> > ![image](https://user-images.githubusercontent.com/34989188/186441026-109c60eb-a32f-4f73-9d99-4c66666564d4.png)
> 
> That's how it should look.

It looks the same no?

Your twitch streams displays the stream in low res (480p) during the ad break right ?

**Comment by StevensND** [comment]
> > > ![image](https://user-images.githubusercontent.com/34989188/186441067-7d6f1078-4a2d-4c61-92a0-3ffa724da1ad.png)
> > > ![image](https://user-images.githubusercontent.com/34989188/186441026-109c60eb-a32f-4f73-9d99-4c66666564d4.png)
> > 
> > 
> > That's how it should look.
> 
> It looks the same no?
> 
> Your twitch displays the stream in low res (480p) during the ad break right ?

Yes. However I'm using [another method](https://github.com/pixeltris/TwitchAdSolutions#applying-a-script-ublock-origin) this works using uBlock Origin Extension (I'm using the notify-strip ublock permalink method) so I don't know if "Commercial Break In Progess" dissapear for you.

**Comment by cleanlock** [comment]
> 

The uBlock method works the same way as the extension for Chrome. It should disappear by using EditThisCookie. It worked for me and several other people too. :)

**Comment by StevensND** [comment]
> > 
> 
> The uBlock method works the same way as the extension for Chrome. It should disappear by using EditThisCookie. It worked for me and several other people too. :)

I guess it depends on which version you're using. Notify-strip/swap were updated but the vaft option (which is based on this extension) not. Still on v5.4.0. I started having the "Commercial Break In Progress" screen yesterday using the vaft option so my fix was switch to notify-strip option.

**Comment by DragonRepairman** [comment]
The EditCookies method stopped working for me about an hour ago.

**Comment by skywatcher77** [comment]
This works for me on Firefox using cookie-editor extension, followed the screens above and disabled twitch adblock.

**Comment by KhalidAlotaibiSA** [comment]
Having the same issue started today, any fix for it? or did Twitch win?

FireFox latest version 103.0.2
Twitch Adblock latest version 5.4.1

![Screenshot_1](https://user-images.githubusercontent.com/47940351/186774506-3024ad23-4887-4641-a1bb-af22086f9a71.png)

**Comment by Darxide23** [comment]
The TTV LOL extension still works for now at least.

**Comment by StevensND** [comment]
> The TTV LOL extension still works for now at least.

Not working for me (I got adds). Purple Ads Blocker works but sometimes it lags. Alternate Player for Twitch.tv gives me delay (I guess I've to play with settings).

**Comment by TheGershon** [comment]
I'm having good results using the vaft userscript from https://github.com/pixeltris/TwitchAdSolutions right now & disabling this extension. Seems to do the usual temporary 480p to your default res once the ads are done.

**Comment by Darxide23** [comment]
> > The TTV LOL extension still works for now at least.
> 
> Not working for me (I got adds). Purple Ads Blocker works but sometimes it lags. Alternate Player for Twitch.tv gives me delay (I guess I've to play with settings).

It's working for me still, so I don't know what you've done wrong. Alternate Player is a last resort because it doesn't have low-latency mode so you get big delays to the streamer.

**Comment by StevensND** [comment]
> I'm having good results using the vaft userscript from https://github.com/pixeltris/TwitchAdSolutions right now & disabling this extension. Seems to do the usual temporary 480p to your default res once the ads are done.

I back to uBlock Origin method + vaft. Working for me too.

**Comment by hazelinterlude** [comment]
> The TTV LOL extension still works for now at least.

TTV LOL works for me still too

**Comment by cleanlock** [comment]
Fixed
