### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by sirbnjmn** [cleanlock/VideoAdBlockForTwitch#61]
displaying "Commercial Break in Progress" when trying to block ads.

**Comment by kli885** [comment]
Seems Twitch updated something with their ads. I'm seeing the same thing

**Comment by Thelgow** [comment]
Yes, it looks like the jig is up. Stopped working for me an hour ago after a reboot.

**Comment by immolated1** [comment]
Confirmed.

**Comment by Erumite** [comment]
See: https://github.com/cleanlock/VideoAdBlockForTwitch/issues/57

**Comment by cleanlock** [comment]
Fixed.
