### ISSUE TITLE
RIP?

### ISSUE THREAD

**Issue by sahlaysta** [cleanlock/VideoAdBlockForTwitch#62]
new twitch anti-adblock feature https://help.twitch.tv/s/article/ad-experience-on-twitch?language=en_US

Screenshot:
<img src="https://i.imgur.com/uw6yilW.png"/>

**Comment by Oscuro87** [comment]
Same just got it todayu for the first time

**Comment by ljara2106** [comment]
Damn same here - can it be fixed?

**Comment by horst789github** [comment]
+1

**Comment by phrenocon** [comment]
Yep, same here. Broken. RIP

**Comment by mystixa** [comment]
That is it partially working and blocking the ad. Its just gotta be fixed to restitch the vid again. Still working for me most of the time, catching ads the regular way with just a few of these purple screens.

**Comment by Kylix-Tyfurious** [comment]
+1

**Comment by Osyruu** [comment]
Duplicated #57

**Comment by Artis84** [comment]
pls fix it

**Comment by cleanlock** [comment]
Fixed. Thanks to @pixeltris <3
