### ISSUE TITLE
Cleanlock is taking down the working extensions now.

### ISSUE THREAD

**Issue by FredCodeFinally** [cleanlock/VideoAdBlockForTwitch#64]
https://github.com/FredCodeFinally/AdblockForTwitch/issues/1

**Comment by cleanlock** [comment]
That is not even true. I couldn't care less about other clones as mine is one as well.

**Comment by FredCodeFinally** [comment]
"Nice clone btw" https://github.com/FredCodeFinally/AdblockForTwitch/issues/1

Contact form
Country of residence
India
Full legal name
Akshay ***
Company name
Twitch Adblock
Full legal name of the copyright holder you represent
Akshay ***
Contact email address
[alway***@gmail.com](mailto:alway***@gmail.com)
Identify and describe the copyrighted work
The copyrighted work includes the content which you can see on the webstore of the extension item. They have included the same content as we have in the webstore description. Then on the further inspection we found the extension source code itself is structured the same as we have. This copyrighted item is nothing but a replica made from the inspiration of our item. They have only changed the UI.
Where can we see an authorized example of the work?
https://chrome.google.com/webstore/detail/twitch-adblock/ljhnljhabgjcihjoihakgdiicdjncpkd
Allegedly infringing URLs
https://chrome.google.com/webstore/detail/adblock-for-twitch/doblogaebbpmpfpohfflgjfebejldofc/
I have a good faith belief that use of the copyrighted materials described above as allegedly infringing is not authorized by the copyright owner, its agent, or the law.
Please check to confirm
The information in this notification is accurate and I swear, under penalty of perjury, that I am the copyright owner or am authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.
Please check to confirm
Signature
Akshay ***

**Comment by cleanlock** [comment]
That's definitely not me. I got better stuff to do than DMCA'ing some random extension. MUst've been someone from the Discord, but surely not me. And I'm not from India as I stated before.

**Comment by FredCodeFinally** [comment]
Well I'm glad you don't care about clones, I'm not sure how they handle false DMCA's but I have the address anyway, so we will see.
