### ISSUE TITLE
Version 5.5.0 for the Microsoft Edge

### ISSUE THREAD

**Issue by DyonR** [cleanlock/VideoAdBlockForTwitch#66]
Could the newest version, 5.5.0 as of writing, also get submitted to the Microsoft Edge Add-ons?

**Comment by cleanlock** [comment]
![image](https://user-images.githubusercontent.com/32986026/188329126-febad092-d244-4aa1-bf32-7b85d3ec1342.png)

Already done.. Microsoft is just omega slow. I really hate that company...

**Comment by DyonR** [comment]
Awesome, thanks for the info. Quite annoying that Microsoft is so slow.

**Comment by cleanlock** [comment]
In the meantime, you should download it directly from the Chrome store. Just add the Chrome store to your Edge Browser whitelist.
