### ISSUE TITLE
Missing bracket will cause check to always fail.

### ISSUE THREAD

**Issue by MegaScience** [cleanlock/VideoAdBlockForTwitch#71]
https://github.com/cleanlock/VideoAdBlockForTwitch/blob/72676a353d0e51e0beb561e10b8f6ae9b5d37d35/firefox/content.js#L210

Because the closing bracket is missing on the referenced line, the query would always fail, resulting in the entire block below never being run.

**Comment by cleanlock** [comment]
There's no bracket necessary? Did you read the code properly?

**Comment by MegaScience** [comment]
Fascinating, it does still work. It's assuming the closing bracket, though, which isn't behavior to rely on. But I'll close this, then.
