### ISSUE TITLE
Would you consider making a Userscript variant?

### ISSUE THREAD

**Issue by Jaladhjin** [cleanlock/VideoAdBlockForTwitch#77]
Hey hey thanks for fighting the good fight against the purple ads 🤘😎🤘

I was wondering about a Userscript variant for Grease/Tampermonkey as a matter of personal preference primarily for 2 reasons.

Reason #1 It's nice to not have to worry about most likely the Chrome store deciding to pull a plugin down.

Reason #2 Userscript updates can be pushed out a lot more freely than having to be approved especially in again the Chrome store more so than Firefox.

If not hey np np just wanted to ask & get you thinking about that too what'd happen if Chrome decided to come for the plugin & pull it down from the store 🤔

Regardless thanks again for the plugin!

**Comment by muleyo** [comment]
There are user scripts out there @ https://github.com/pixeltris/TwitchAdSolutions
