### ISSUE TITLE
Squad Stream Support

### ISSUE THREAD

**Issue by creedda** [cleanlock/VideoAdBlockForTwitch#78]
This Extension doesn't work during squad streams.

https://help.twitch.tv/s/article/how-to-use-squad-stream?language=en_US

Just wanted to let you know!

**Comment by tombomb** [comment]
https://github.com/cleanlock/VideoAdBlockForTwitch/blob/master/firefox/content.js#L509

**Comment by creedda** [comment]
> https://github.com/cleanlock/VideoAdBlockForTwitch/blob/master/firefox/content.js#L509

Thanks! Guess this becomes a feature request then. Appreciate the add-on!

**Comment by muleyo** [comment]
not planned, sorry.
