### ISSUE TITLE
I loaded but get error  "manifest_version": 2 - Issue Fixed

### ISSUE THREAD

**Issue by daimonxp** [cleanlock/VideoAdBlockForTwitch#8]
Hi, I loaded this git hub after seeing reviews the extension reports in chrome error and highlights
 "manifest_version": 2, 

any idea?

**Comment by HatterTheMadd** [comment]
+ Loaded new master zip.
I didn't get any errors with the new version.
(Just wanted to check)
![image](https://user-images.githubusercontent.com/25492218/160893547-025fa165-9d6c-4101-8d1f-96821e366da2.png)

**Comment by mikirobles** [comment]
I am getting this error with the new version on Opera GX
![image](https://user-images.githubusercontent.com/25488110/160893828-ad949ae2-f764-4784-b734-295ba6d3de08.png)

**Comment by cleanlock** [comment]
Hi, yes the errors disappeared. I just tested the version and it seems like that the extension doesn't block Twitch Ads anymore when using manifest v3.

I had to revert the changes to manifest.json. The errors which appear can usually be ignored as the extension should work at least til next year. Google forces extensions to upgrade to manifest v3 in 2023.

Don't worry, I think here are a lot of people around which can help and contribute to get this done. :)

**Comment by HatterTheMadd** [comment]
+ Adding to open issue for Manifest v3
Chrome is reporting: 'webRequestBlocking' requires manifest version of 2 or lower.

**Comment by daimonxp** [comment]
Yeah I think it works now, I get same error as the image posted now. Also saw the thing about be good till about 2023. Hopefully it can get up updated and continued support.

**Comment by pwltr** [comment]
@cleanlock Are you sure it's not blocking ads without `"webRequest"` `"webRequestBlocking"` permissions? Seems to me it doesn't even use that API. Trying to test this but not getting any ads at all right now even without any extension running. The one time you actually want ads lol.

**Comment by cleanlock** [comment]
> @cleanlock Are you sure it's not blocking ads without `"webRequest"` `"webRequestBlocking"` permissions? Seems to me it doesn't even use that API. Trying to test this but not getting any ads at all right now even without any extension running. The one time you actually want ads lol.

Not sure. Still seems like Manifest v3 doesn't allow inline scripts. I tried to execute the needed code from another file. The errors are gone, but ads are still present.

**Comment by daimonxp** [comment]
Seem the webstore original was removed by google. Its no longer accessible.

**Comment by cleanlock** [comment]
> Seem the webstore original was removed by google. Its no longer accessible.

That's good and deserved tbh

**Comment by daimonxp** [comment]
> > Seem the webstore original was removed by google. Its no longer accessible.
> 
> That's good and deserved tbh

yeah just sucks others don't have a easy option. Most won't know about this github. Unless he I don't know if he can do this block me from posting on there. or if google allows that.

**Comment by cleanlock** [comment]
> > > Seem the webstore original was removed by google. Its no longer accessible.
> > 
> > 
> > That's good and deserved tbh
> 
> yeah just sucks others don't have a easy option. Most won't know about this github. Unless he I don't know if he can do this block me from posting on there. or if google allows that.

Well yeah, I tried to spread this GitHub as much as possible. I hope that we get this updated to Manifest v3 so it actually works properly again and can be published on the Chrome Webstore.

We'll see :)

**Comment by daimonxp** [comment]
Well its all over reddit about it. I posted your link on it. There.
https://www.reddit.com/r/Adblock/
There's to posts, and I'm trying to get ppls attention to this github. But not many are reading it.

**Comment by daimonxp** [comment]
> > > > Seem the webstore original was removed by google. Its no longer accessible.
> > > 
> > > 
> > > That's good and deserved tbh
> > 
> > 
> > yeah just sucks others don't have a easy option. Most won't know about this github. Unless he I don't know if he can do this block me from posting on there. or if google allows that.
> 
> Well yeah, I tried to spread this GitHub as much as possible. I hope that we get this updated to Manifest v3 so it actually works properly again and can be published on the Chrome Webstore.
> 
> We'll see :)

Me too. Tyvm for this, I will and have been trying to spread this but its hard. BTW I figured not only did he delete the github, he deleted his reddit account the original dev.  Check this out. https://www.reddit.com/user/Saucee888/

**Comment by cleanlock** [comment]
> > > > > Seem the webstore original was removed by google. Its no longer accessible.
> > > > 
> > > > 
> > > > That's good and deserved tbh
> > > 
> > > 
> > > yeah just sucks others don't have a easy option. Most won't know about this github. Unless he I don't know if he can do this block me from posting on there. or if google allows that.
> > 
> > 
> > Well yeah, I tried to spread this GitHub as much as possible. I hope that we get this updated to Manifest v3 so it actually works properly again and can be published on the Chrome Webstore.
> > We'll see :)
> 
> Me too. Tyvm for this, I will and have been trying to spread this but its hard. BTW I figured not only did he delete the github, he deleted his reddit account the original dev. Check this out. https://www.reddit.com/user/Saucee888/ What a day, and how random this all is.

Haha, yeah I've seen it. Kinda insane actually. Imagine publishing some shady stuff secretly and then ending up deleting everything, including your accounts.

**Comment by cleanlock** [comment]
Update to Manifest v3 has been pushed to the dev-Branch. I also released a pre-release (v5.3.5). You can find it here: https://github.com/cleanlock/VideoAdBlockForTwitch/releases

**Comment by daimonxp** [comment]
Ok, so, just fyi, when pushed to the store. Remember it just goa massive bad rap on it. and bad name as an extension. Are you going to specify this ain't the same as the last one?  just figured I'd ask.

**Comment by cleanlock** [comment]
> Ok, so, just fyi, when pushed to the store. Remember it just got a massive bad rap on it. and bad name as an extension. Are you going to specify this ain't the same as the last one? just figured I'd ask.

I'm publishing it under the old name, but I added into the description that it's not being maintained by the original author.

**Comment by daimonxp** [comment]
> > Ok, so, just fyi, when pushed to the store. Remember it just got a massive bad rap on it. and bad name as an extension. Are you going to specify this ain't the same as the last one? just figured I'd ask.
> 
> I'm publishing it under the old name, but I added into the description that it's not being maintained by the original author.
> 
> Tbh I think he deleted the extension by himself, not Google. The Chrome extension disappeared at the same time as the Edge extension.

Ok, I'm just protecting you and everyone contributing. I figured we have to think of these things.

**Comment by cleanlock** [comment]
> > > Ok, so, just fyi, when pushed to the store. Remember it just got a massive bad rap on it. and bad name as an extension. Are you going to specify this ain't the same as the last one? just figured I'd ask.
> > 
> > 
> > I'm publishing it under the old name, but I added into the description that it's not being maintained by the original author.
> > Tbh I think he deleted the extension by himself, not Google. The Chrome extension disappeared at the same time as the Edge extension.
> 
> Ok, I'm just protecting you and everyone contributing. I figured we have to think of these things.

I understand your thoughts and they make sense. I thought it's good to take the old name so people will actually find it immediately. A lot of people haven't even noticed what happened.

**Comment by daimonxp** [comment]
> > > > Ok, so, just fyi, when pushed to the store. Remember it just got a massive bad rap on it. and bad name as an extension. Are you going to specify this ain't the same as the last one? just figured I'd ask.
> > > 
> > > 
> > > I'm publishing it under the old name, but I added into the description that it's not being maintained by the original author.
> > > Tbh I think he deleted the extension by himself, not Google. The Chrome extension disappeared at the same time as the Edge extension.
> > 
> > 
> > Ok, I'm just protecting you and everyone contributing. I figured we have to think of these things.
> 
> I understand your thoughts and they make sense. I thought it's good to take the old name so people will actually find it immediately. A lot of people haven't even noticed what happened.

Very true, and I apperciate all you've done and others on this. Its amazing. Just since the name was taken down by google wouldn't they deny it. Then again I don't know how extension submissions work with google.

**Comment by cleanlock** [comment]
> > > > > Ok, so, just fyi, when pushed to the store. Remember it just got a massive bad rap on it. and bad name as an extension. Are you going to specify this ain't the same as the last one? just figured I'd ask.
> > > > 
> > > > 
> > > > I'm publishing it under the old name, but I added into the description that it's not being maintained by the original author.
> > > > Tbh I think he deleted the extension by himself, not Google. The Chrome extension disappeared at the same time as the Edge extension.
> > > 
> > > 
> > > Ok, I'm just protecting you and everyone contributing. I figured we have to think of these things.
> > 
> > 
> > I understand your thoughts and they make sense. I thought it's good to take the old name so people will actually find it immediately. A lot of people haven't even noticed what happened.
> 
> Very true, and I apperciate all you've done and others on this. Its amazing. Just since the name was taken down by google wouldn't they deny it. Then again I don't know how extension submissions work with google.

I guess we'll find out. 

![image](https://user-images.githubusercontent.com/32986026/160953641-d1e9afdd-ac3a-46b7-82a6-7378c8ec50da.png)

**Comment by daimonxp** [comment]
If not we can come up with some clever name for ppl to find it. Again thank you so very much for this, and everyone.

**Comment by daimonxp** [comment]
Ok that version works might want to update the current one to that one. the 5.3.4 manifest doesn't work anymore.

**Comment by cleanlock** [comment]
So far they're both working fine for me.

**Comment by daimonxp** [comment]
Yeah I tired 5.3.4 and gives me the above error I posted the screen shot when trying to load it. Not sure.

**Comment by cleanlock** [comment]
Hm, weird. it should work. I re-released 5.3.4 tho. Anyway, both versions work. I'll merge v5.3.5 into master soon.

**Comment by daimonxp** [comment]
[[https://imgur.com/a/uHdoxy8](https://github.com/cleanlock/VideoAdBlockForTwitch/issues/url)](url)

**Comment by cleanlock** [comment]
master is still v5.3.4. Seems like the manifest.json file is not existing in your folder?

**Comment by daimonxp** [comment]
![MANIFESTT](https://user-images.githubusercontent.com/102687585/160961185-ea8d974a-8df1-47e3-aa81-1f15c38da798.png)

**Comment by cleanlock** [comment]
Not sure why it would not load for you. Delete the whole folder and zip and re-download please

**Comment by daimonxp** [comment]
WTF, now 5.3.5 won't load the manifest is itanother extension messing with it?

**Comment by cleanlock** [comment]
![image](https://user-images.githubusercontent.com/32986026/160961625-e22d72b5-8bda-4805-9f79-1522886d0a64.png)

Both are loading without any issues :D

**Comment by daimonxp** [comment]
haha you got both of them yeah its a user error Im tired, I just directed it to the folder not the folder inside the folder. lol

**Comment by cleanlock** [comment]
No worries, happens :)

**Comment by daimonxp** [comment]
Been troubleshooting all day brain is a mush. My apologies for the urgency.

**Comment by cleanlock** [comment]
It's all good haha. I'm always thankful for troubleshooting :) good that everything is working!

**Comment by daimonxp** [comment]
Wish I could script/code, or I would work on it with you as well.  I work remotely on data center severs for HP.

**Comment by flyingwolf79** [comment]
Heads up, I pinged a friend at Amazon in the affiliate department with his TOS violating usage of injecting AFF code. 

FAFO

**Comment by daimonxp** [comment]
Well I wouldn't be surprised if he didn't delete everything. He deleted his extensions from every source/edge/firefox/chrome. Then deleted his Reddit accout. Then deleted his source code in github. Though it can be pulled up by wayback machine I'm sure.
