### ISSUE TITLE
Discord link and addon are both missing from Google

### ISSUE THREAD

**Issue by CrazedBanana** [cleanlock/VideoAdBlockForTwitch#80]
I'm not sure where else to put this. The discord link does not work so I can't join for updates. Can someone please link it here so I can join and follow the updates?

**Comment by muleyo** [comment]
Discord link works just fine, Google has taken down the extension for now due to a fake DMCA. Just about time that it's back.

If the link doesn't work for you, then you might be banned because you simply misbehaved.

**Comment by CrazedBanana** [comment]
I am not banned. I left the channel by mistake when cleaning out my discord. I even attempted to join from a second discord and it would not go through. Are you able to link discord here so I can try again?

**Comment by CrazedBanana** [comment]
> 

It works, I uninstall and re-installed discord. I will delete this thread if I can. If not you can delete if you are able too.

**Comment by muleyo** [comment]
Just use the link in the readme.

**Comment by CrazedBanana** [comment]
It works, thank you!
