### ISSUE TITLE
[Suggestion] Userscript variant?

### ISSUE THREAD

**Issue by TsukiZero** [cleanlock/VideoAdBlockForTwitch#91]
Since it's quicker to modify and Pixeltris is pretty much waiting for this one to do it instead.

**Comment by KevinStaude** [comment]
https://github.com/pixeltris/TwitchAdSolutions/blob/master/vaft/vaft.user.js

**Comment by TsukiZero** [comment]
Ah, so the one from TAS is up to date? Thought it wasn't.
